//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSync.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost:32422")]
        public string cServer {
            get {
                return ((string)(this["cServer"]));
            }
            set {
                this["cServer"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:32422/BaseConService.asmx")]
        public string AutoSync_BaseCon_BaseConService {
            get {
                return ((string)(this["AutoSync_BaseCon_BaseConService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:32422/SyncManufactureRecBill.asmx")]
        public string AutoSync_SyncWo_SyncManufactureRecBill {
            get {
                return ((string)(this["AutoSync_SyncWo_SyncManufactureRecBill"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:32422/SyncMaterialReqBill.asmx")]
        public string AutoSync_SyncProduce_SyncMaterialReqBill {
            get {
                return ((string)(this["AutoSync_SyncProduce_SyncMaterialReqBill"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:32422/SyncMoveInWarehsBill.asmx")]
        public string AutoSync_SyncTransferStore_SyncMoveInWarehsBill {
            get {
                return ((string)(this["AutoSync_SyncTransferStore_SyncMoveInWarehsBill"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:32422/SyncMoveIssueBill.asmx")]
        public string AutoSync_SyncTransferDelivery_SyncMoveIssueBill {
            get {
                return ((string)(this["AutoSync_SyncTransferDelivery_SyncMoveIssueBill"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:32422/SyncPurReceivalBill.asmx")]
        public string AutoSync_SyncPoStore_SyncOrder {
            get {
                return ((string)(this["AutoSync_SyncPoStore_SyncOrder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:32422/SyncSaleIssueBill.asmx")]
        public string AutoSync_SyncSaleDelivery_SyncSaleIssueBill {
            get {
                return ((string)(this["AutoSync_SyncSaleDelivery_SyncSaleIssueBill"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=JWMSY_2015;Persist Security Info=True;User ID" +
            "=sa;Password=kingdee")]
        public string WmsCon {
            get {
                return ((string)(this["WmsCon"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:32422/EasOrder.asmx")]
        public string AutoSync_EasOrderService_EasOrder {
            get {
                return ((string)(this["AutoSync_EasOrderService_EasOrder"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eas750test20151226")]
        public string EasDataCenter {
            get {
                return ((string)(this["EasDataCenter"]));
            }
            set {
                this["EasDataCenter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yofoto")]
        public string EasUserName {
            get {
                return ((string)(this["EasUserName"]));
            }
            set {
                this["EasUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("000000")]
        public string EasUserPwd {
            get {
                return ((string)(this["EasUserPwd"]));
            }
            set {
                this["EasUserPwd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.202:7888/ormrpc/services/WSWSYofotoFacade")]
        public string EasApproveUrl {
            get {
                return ((string)(this["EasApproveUrl"]));
            }
            set {
                this["EasApproveUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.1.202:7888/ormrpc/services/EASLogin")]
        public string EasLoginUrl {
            get {
                return ((string)(this["EasLoginUrl"]));
            }
            set {
                this["EasLoginUrl"] = value;
            }
        }
    }
}
